language: node_js
node_js:
  - "0.10"

before_script:
  - export DISPLAY=:99.0
  - export PHANTOMJS_BIN=/usr/local/phantomjs/bin/phantomjs
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - npm install -gq bower codeclimate-test-reporter # coveralls
  - bower install --dev --config.interactive=0
  - gulp --version
  - bower --version
  - date --rfc-2822

script:
  - gulp jshint karma:travis

after_script:
  - cat test/coverage/*/lcov.info | codeclimate

addons:
  code_climate:
    repo_token: 0f7f0517236dc12f9b55320c5e93c93123907302246ad3ddc0bfe793546f10e5
